import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Varela, Abhaya_Libre } from "next/font/google";

// const inter = Inter({ subsets: ['latin'] })
const varela = Varela({ subsets: ["latin-ext"], weight: "400" });

const inter = Abhaya_Libre({ subsets: ["latin"], weight: "400" });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <body className={inter.className}>{children}</body> */}
      <body className={varela.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
